import { useState } from 'react';
import { router } from 'expo-router';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { BirthDetails, calculateCompatibility, CompatibilityResult } from '../src/api/jyotisha';
import { BirthDetailsFields, HYDERABAD_BIRTH_DETAILS } from '../src/components/BirthDetailsForm';
import { Card } from '../src/components/Card';
import { colors } from '../src/theme';
import { usePanchangamSettings } from '../src/settings';

export default function CompatibilityScreen() {
  const { language } = usePanchangamSettings();
  const telugu = language === 'te';
  const [bride, setBride] = useState<BirthDetails>(HYDERABAD_BIRTH_DETAILS);
  const [groom, setGroom] = useState<BirthDetails>(HYDERABAD_BIRTH_DETAILS);
  const [result, setResult] = useState<CompatibilityResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [brideDropdownOpen, setBrideDropdownOpen] = useState(false);
  const [groomDropdownOpen, setGroomDropdownOpen] = useState(false);
  const submit = async () => { if (!bride.name.trim() || !groom.name.trim()) { setError(telugu ? 'దయచేసి రెండు పేర్లు నమోదు చేయండి' : 'Please enter both names'); return; } setLoading(true); setError(null); try { setResult(await calculateCompatibility(bride, groom)); } catch (e) { setError(e instanceof Error ? e.message : (telugu ? 'గణన విఫలమైంది' : 'Calculation failed')); } finally { setLoading(false); } };
  return <ScrollView style={styles.screen} contentContainerStyle={styles.shell}><View style={styles.frame}>
    <Pressable accessibilityRole="button" onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable>
    <View style={styles.header}><Text style={styles.eyebrow}>Aṣṭakoota · Guna Milan</Text><Text style={styles.title}>{telugu ? 'వివాహ పొంతన' : 'Marriage compatibility'}</Text><Text style={styles.subtitle}>{telugu ? 'సాంప్రదాయ 36-పాయింట్ల వివాహ పొంతన' : 'Traditional 36-point marriage compatibility'}</Text></View>
    <View style={styles.content}><Card style={styles.formCard}><BirthDetailsFields title={telugu ? 'వధువు' : 'Bride'} details={bride} onChange={setBride} onPlaceDropdownVisibleChange={setBrideDropdownOpen} /></Card><Card style={styles.formCard}><BirthDetailsFields title={telugu ? 'వరుడు' : 'Groom'} details={groom} onChange={setGroom} onPlaceDropdownVisibleChange={setGroomDropdownOpen} /></Card><Pressable accessibilityRole="button" onPress={submit} disabled={brideDropdownOpen || groomDropdownOpen} style={[styles.primary, (brideDropdownOpen || groomDropdownOpen) && styles.primaryHidden]}>{loading ? <ActivityIndicator color={colors.white} /> : <Text style={styles.primaryText}>{telugu ? 'పొంతన చూడండి' : 'Check compatibility'} →</Text>}</Pressable>{error && <Text style={styles.error}>{error}</Text>}{result && <Results result={result} telugu={telugu} />}</View>
  </View></ScrollView>;
}
function Results({ result, telugu }: { result: CompatibilityResult; telugu: boolean }) { return <View style={styles.results}><Card style={styles.scoreCard}><Text style={styles.scoreLabel}>{telugu ? 'గుణ మిలన్ స్కోరు' : 'Guna Milan score'}</Text><Text style={styles.score}>{result.total_points}<Text style={styles.outOf}> / {result.max_points}</Text></Text><Text style={styles.verdict}>{result.verdict}</Text><Text style={styles.facts}>{telugu ? 'వధువు' : 'Bride'}: {result.bride.nakshatra} · {result.bride.rashi}{'\n'}{telugu ? 'వరుడు' : 'Groom'}: {result.groom.nakshatra} · {result.groom.rashi}</Text></Card><Card><Text style={styles.section}>{telugu ? 'ఎనిమిది కూటలు' : 'Eight kootas'}</Text>{result.kootas.map((item) => <View key={item.koota} style={styles.koota}><Text style={styles.kootaName}>{item.koota}</Text><Text style={styles.kootaScore}>{item.points} / {item.max_points}</Text><Text style={styles.kootaNote}>{item.note}</Text></View>)}</Card>{result.doshas.map((dosha) => <Card key={dosha.name} style={styles.dosha}><Text style={styles.section}>{dosha.name}</Text><Text style={styles.kootaNote}>{dosha.note}</Text></Card>)}<Text style={styles.note}>{result.note}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.creamDeep }, shell: { alignItems: 'center' }, frame: { width: '100%', maxWidth: 430, minHeight: '100%', backgroundColor: colors.cream, paddingBottom: 28 }, back: { marginLeft: 16, marginTop: 48, width: 44, height: 44, borderRadius: 14, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' }, backText: { color: colors.maroon, fontSize: 30, lineHeight: 34 }, header: { margin: 16, marginTop: 12, borderRadius: 20, backgroundColor: colors.maroon, padding: 16 }, eyebrow: { color: colors.gold, fontWeight: '800', fontSize: 11, textTransform: 'uppercase' }, title: { color: colors.white, fontSize: 24, fontWeight: '800', marginTop: 4 }, subtitle: { color: '#ffe7d8', fontSize: 12, lineHeight: 18, marginTop: 4 }, content: { paddingHorizontal: 16, gap: 10 }, formCard: { zIndex: 10 }, primary: { minHeight: 46, backgroundColor: colors.maroon, alignItems: 'center', justifyContent: 'center', borderRadius: 13 }, primaryHidden: { opacity: 0 }, primaryText: { color: colors.white, fontWeight: '800', fontSize: 14 }, error: { color: colors.maroon, fontSize: 12 }, results: { gap: 10 }, scoreCard: { backgroundColor: colors.peach, borderColor: '#ffd7b8' }, scoreLabel: { color: colors.orange, fontSize: 11, fontWeight: '800', textTransform: 'uppercase' }, score: { color: colors.maroon, fontSize: 36, lineHeight: 42, fontWeight: '800', marginTop: 3 }, outOf: { fontSize: 18 }, verdict: { color: colors.ink, fontSize: 13, lineHeight: 20, marginTop: 4, fontWeight: '700' }, facts: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 9 }, section: { color: colors.orange, fontSize: 11, fontWeight: '800', textTransform: 'uppercase' }, koota: { borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 9, marginTop: 9 }, kootaName: { color: colors.ink, fontSize: 14, fontWeight: '800' }, kootaScore: { color: colors.maroon, fontSize: 13, fontWeight: '800', marginTop: 2 }, kootaNote: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 2 }, dosha: { backgroundColor: colors.peach, borderColor: '#ffd7b8' }, note: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 2 }, });
