import { useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { calculateHoroscope, HoroscopeResult } from '../src/api/jyotisha';
import { BirthDetailsFields, HYDERABAD_BIRTH_DETAILS } from '../src/components/BirthDetailsForm';
import { Card } from '../src/components/Card';
import { colors } from '../src/theme';

export default function HoroscopeScreen() {
  const { mode } = useLocalSearchParams<{ mode?: string }>();
  const doshaMode = mode === 'doshas';
  const [details, setDetails] = useState(HYDERABAD_BIRTH_DETAILS);
  const [result, setResult] = useState<HoroscopeResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [placeDropdownOpen, setPlaceDropdownOpen] = useState(false);
  const submit = async () => { if (!details.name.trim()) { setError('Please enter a name'); return; } setLoading(true); setError(null); try { setResult(await calculateHoroscope(details, doshaMode)); } catch (e) { setError(e instanceof Error ? e.message : 'Calculation failed'); } finally { setLoading(false); } };
  return <ScrollView style={styles.screen} contentContainerStyle={styles.shell}><View style={styles.frame}>
    <Pressable accessibilityRole="button" onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable>
    <View style={styles.header}><Text style={styles.eyebrow}>{doshaMode ? 'Birth nakshatra check' : 'SoHum Jyotisha'}</Text><Text style={styles.title}>{doshaMode ? 'శిశు జనన దోషం' : 'జాతకం'}</Text><Text style={styles.subtitle}>{doshaMode ? 'Gandamool, Manglik and Kaal Sarp flags' : 'Native chart, divisional charts and active daśā'}</Text></View>
    <View style={styles.content}><Card><BirthDetailsFields details={details} onChange={setDetails} onPlaceDropdownVisibleChange={setPlaceDropdownOpen} /><Pressable accessibilityRole="button" onPress={submit} disabled={placeDropdownOpen} style={[styles.primary, placeDropdownOpen && styles.primaryHidden]}>{loading ? <ActivityIndicator color={colors.white} /> : <Text style={styles.primaryText}>{doshaMode ? 'Check birth nakshatra' : 'Calculate horoscope'} →</Text>}</Pressable>{error && <Text style={styles.error}>{error}</Text>}</Card>
    {result && (doshaMode ? <DoshaResults result={result} /> : <HoroscopeResults result={result} />)}</View>
  </View></ScrollView>;
}
function HoroscopeResults({ result }: { result: HoroscopeResult }) { const moon = result.planets.find((p) => p.name === 'Moon'); const d1 = result.charts.D1?.points ?? []; return <View style={styles.results}><Card><Text style={styles.section}>Chart essentials</Text><Text style={styles.big}>{result.subject.name || 'Birth chart'}</Text><Text style={styles.line}>Lagna: {result.ascendant.sign} · {result.ascendant.nakshatra} pada {result.ascendant.pada}</Text><Text style={styles.line}>Moon: {moon?.sign} · {moon?.nakshatra} pada {moon?.pada}</Text></Card><Card><Text style={styles.section}>Active Vimshottari daśā</Text>{result.dashas.active_path.map((period) => <Text key={`${period.level}-${period.lord}`} style={styles.line}>{period.level}: {period.lord} · ends {new Date(period.ends_at).toLocaleDateString('en-IN')}</Text>)}</Card><Card><Text style={styles.section}>D1 placements</Text>{d1.map((point) => <Text key={point.name} style={styles.line}>{point.name} · {point.sign} · House {point.house}</Text>)}</Card><Text style={styles.disclaimer}>{result.disclaimer}</Text></View>; }
function DoshaResults({ result }: { result: HoroscopeResult }) { const entries = Object.values(result.doshas ?? {}); return <View style={styles.results}><Card><Text style={styles.section}>Birth nakshatra</Text><Text style={styles.big}>{entries.find((item) => item.dosha === 'Gandmool')?.birth_nakshatra ?? '—'}</Text></Card>{entries.map((item) => <Card key={item.dosha} style={item.present ? styles.alertCard : undefined}><Text style={styles.section}>{item.dosha}</Text><Text style={styles.big}>{item.present ? 'Present' : 'Not present'}</Text>{item.severity && <Text style={styles.line}>Severity: {item.severity}</Text>}{item.remedies_te && <Text style={styles.line}>{item.remedies_te}</Text>}{item.note && <Text style={styles.disclaimer}>{item.note}</Text>}</Card>)}</View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.creamDeep }, shell: { alignItems: 'center' }, frame: { width: '100%', maxWidth: 430, minHeight: '100%', backgroundColor: colors.cream, paddingBottom: 28 }, back: { marginLeft: 16, marginTop: 48, width: 44, height: 44, borderRadius: 14, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' }, backText: { color: colors.maroon, fontSize: 30, lineHeight: 34 }, header: { margin: 16, marginTop: 12, borderRadius: 20, backgroundColor: colors.maroon, padding: 16 }, eyebrow: { color: colors.gold, fontWeight: '800', fontSize: 11, textTransform: 'uppercase' }, title: { color: colors.white, fontSize: 24, fontWeight: '800', marginTop: 4 }, subtitle: { color: '#ffe7d8', fontSize: 12, lineHeight: 18, marginTop: 4 }, content: { paddingHorizontal: 16, gap: 10 }, primary: { minHeight: 46, backgroundColor: colors.maroon, alignItems: 'center', justifyContent: 'center', borderRadius: 13, marginTop: 14 }, primaryHidden: { opacity: 0 }, primaryText: { color: colors.white, fontWeight: '800', fontSize: 14 }, error: { color: colors.maroon, fontSize: 12, marginTop: 10 }, results: { gap: 10 }, section: { color: colors.orange, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.3 }, big: { color: colors.ink, fontSize: 19, fontWeight: '800', marginTop: 5 }, line: { color: colors.ink, fontSize: 13, lineHeight: 20, marginTop: 4 }, alertCard: { backgroundColor: colors.peach, borderColor: '#ffd7b8' }, disclaimer: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 8 }, });
